### ISSUE TITLE
Pre-trained weight files

### ISSUE THREAD

**Issue by Zhijin-Ge** [ydc123/Meta_Surrogate_Model#1]
Hello Dingcheng Yang, can you provide pre-trained weight files for this project? Does the weight file in [Dark_Surrogate_Model](https://github.com/ydc123/Dark_Surrogate_Model) include the weight of this MSM model? I am looking forward to your reply. Thank you sincerely.

**Comment by ydc123** [comment]
Thanks for your interest in our work. I have just added the model weights of an MSM-based ResNet18 to the [Dark_Surrogate_Model](https://github.com/ydc123/Dark_Surrogate_Model). Please see `resnet18_MTA_stage3.pth.tar` in Baidu Netdist ([link, 链接](https://pan.baidu.com/s/1wSH8GKH6KlXJv5NSjpq-NQ) with password j7fg).
In fact, this is an unofficial repository. I have asked the authors of MSM for their checkpoint, but unfortunately I did not get it. Therefore, I implemented the MSM myself as much as possible based on their paper. The experimental results show that our MSM-based ResNet18 has higher adversarial transferability than the normal ResNet18 when a robust model is considered as the victim model (such as HGD), but worse than our work (Dark Surrogate Model). Interestingly, the our own trained MSM-based ResNet18 was not better than the normal ResNet18 on the normally trained victim models. We tried to check the experimental details, but we did not get better results.
We hope this information is useful for you!

**Comment by Zhijin-Ge** [comment]
I sincerely thank you for your detailed reply and also for the model weights you provided, this information is very useful for me. Best regards and wishes to you.

**Comment by Zhijin-Ge** [comment]
Hi Mr. Yang, sorry to bother you again. There is some problem with loading the model weight, it doesn't load normally, and it seems like the weight file is damaged. Can you use this weight file normally, and if so, could you re-upload it? Sincerely thank you again!
![QQ截图20230708212238](https://github.com/ydc123/Meta_Surrogate_Model/assets/42350897/a3ebb108-8ef0-4b41-9dc6-082cc633d791)

**Comment by ydc123** [comment]
> Hi Mr. Yang, sorry to bother you again. There is some problem with loading the model weight, it doesn't load normally, and it seems like the weight file is damaged. Can you use this weight file normally, and if so, could you re-upload it? Sincerely thank you again! ![QQ截图20230708212238](https://user-images.githubusercontent.com/42350897/251975130-a3ebb108-8ef0-4b41-9dc6-082cc633d791.png)

What is your version of pytorch?This code works fine in my environment (Pytorch 1.10.1).

**Comment by ydc123** [comment]
The above issue seems to be due to some problems with the upload, which resulted in a corrupted file. I have now re-uploaded a weight file resnet18_MTA_stage3.pth (note that the .tar suffix is no longer needed) and it seems to be working.

**Comment by Zhijin-Ge** [comment]
Yes, it works! The latest uploaded weights file works fine. Thank you very, very, very much!
